version: "3.2"

services:
    
    php8:
        build: ./php8
        container_name: app
        volumes:
            - ../:/var/www/oliveira-api
        working_dir: /var/www/oliveira-api
        ports:
            - 9074:9000
        networks:
            - app-oliveira-trust

    nginx:
        image: nginx:latest
        container_name: webserver
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../:/var/www/oliveira-api
            - ./nginx/api-oliveira-trust.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-oliveira-trust

    mysql57:
        image: mysql:5.7.22
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - ../.docker/dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: oliveira_api
            MYSQL_ROOT_PASSWORD: oliveira_api
        networks:
            - app-oliveira-trust

    redis:
        image: redis
        ports:
            - 6379:6379
        restart: always
        networks:
            - app-oliveira-trust

networks:
    app-oliveira-trust:
        driver: bridge
